[package]
name = "atelier-loader"
version = "0.1.0"
authors = ["Karl Bergström <karl.anton.bergstrom@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
type-uuid = "0.1"
crossbeam-channel = "0.4"

atelier-core = { path = "../core", version = "0.1.0", features = ["serde-1"] }
atelier-schema = { path = "../schema", version = "0.1.0", optional = true }
tokio = { version = "0.2", features = ["tcp", "sync", "rt-core", "rt-util", "stream"], optional = true }
tokio-util = { version = "0.3", features = ["compat"], optional = true }
futures-util = { version = "0.3", default-features = false, features = ["io"], optional = true }
futures-channel = { version = "0.3", default-features = false, features = ["alloc"] }
futures-core = { version = "0.3", default-features = false }
capnp = { version = "0.13", optional = true}
capnp-rpc = { version = "0.13", optional = true }
log = { version = "0.4", optional = true }
dashmap = { version = "3", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true}
uuid = { version = "0.8", optional = true }

[dev-dependencies]
atelier-daemon = { path = "../daemon", version = "0.1.0" }
atelier-importer = { path = "../importer", version = "0.1.0" }
uuid = { version = "0.8", features = ["v4"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "0.2", features = ["io-util"] }
futures-io = { version = "0.3" }

[features]
default = ["rpc_loader", "handle"]
rpc_loader = ["atelier-schema", "tokio", "capnp", "capnp-rpc", "log", "dashmap", "tokio-util", "futures-util"]
handle = ["serde", "uuid"]
asset_uuid_macro = ["atelier-core/asset_uuid_macro"]
