[package]
name = "atelier-loader"
version = "0.1.0"
authors = ["Karl Bergström <karl.anton.bergstrom@gmail.com>"]
edition = "2018"
license = "MIT OR Apache-2.0"

[dependencies]
crossbeam-channel = "0.5.0"
atelier-core = { path = "../core", version = "0.1.0", features = ["serde-1"] }
atelier-schema = { path = "../schema", version = "0.1.0", optional = true }
tokio = { version = "1.0", features = ["net", "sync", "rt", "rt-multi-thread"], optional = true }
tokio-util = { version = "0.6.1", features = ["compat"], optional = true }
futures-util = { version = "0.3", default-features = false, features = ["io"], optional = true }
futures-channel = { version = "0.3", default-features = false, features = ["alloc"] }
futures-core = { version = "0.3", default-features = false, features = ["alloc"] }
capnp = { version = "0.14.0", optional = true }
capnp-rpc = { version = "0.14.0", optional = true }
log = "0.4"
dashmap = "4.0.1"
serde = { version = "1", features = ["derive"], optional = true }
uuid = { version = "0.8.2", optional = true }
memmap = { version = "0.7", optional = true }
thread_local = { version = "1.0", optional = true }
bevy_reflect = { git = "https://github.com/bevyengine/bevy.git", version = "0.4.0", optional = true }
bevy_reflect_derive = { git = "https://github.com/bevyengine/bevy.git", version = "0.4.0", optional = true }


[features]
default = ["rpc_io", "handle", "packfile_io"]
packfile_io = [
    "atelier-schema",
    "tokio",
    "capnp",
    "capnp-rpc",
    "tokio-util",
    "futures-util",
    "memmap",
    "thread_local",
]
rpc_io = [
    "atelier-schema",
    "tokio",
    "capnp",
    "capnp-rpc",
    "futures-util",
    "invalidate_path",
]
invalidate_path = ["atelier-core/path_utils"]
handle = ["serde", "uuid"]
bevy_reflect_impls = ["bevy_reflect_derive", "bevy_reflect"]
